combat-features:
  # All time settings are measured in milliseconds
  debug: true
  # The time before a player can attempt to use an ability again. (Prevents spamming)
  global-cooldown: 50
  dodge:
    # A player can dodge via pressing the F keybind (player swap hands). If the player is not in the air the player
    # will be 'thrown' in the direction they are moving. For the duration of the dodge they mitigate any targetted damage taken.
    # A player cannot dodge if they;
    # - are already dodging
    # - are blocking
    # - have no stamina
    enabled: true
    # Amount of particles to spawn during a dodge
    particle-count: 5
    #The warmup before a player can dodge. The dodge can be interrupted if the player takes damage in this time
    warmup: 0
    #For how long is the entity dodging
    duration: 500
    #How strong the dodge is.
    strength: 0.5
    #How much is damage mitigated by - change this to be based on an MMOItems stat later
    mitigation: 0.6
    # Stamina cost of a dodge
    stamina-cost: 75
    # Which damage causes apply to a dodge event. See list here https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    applicable-damage-causes:
      - ENTITY_ATTACK
      - ENTITY_SWEEP_ATTACK
      - PROJECTILE
  block:
    # When a player blocks, a block event is queued which has an expiry time of the specified duration
    # If an attack is made against a player who is blocking, if their block has not expired, then damage is mitigated
    # by the specified amount
    # A player cannot block if they;
    # - have a cooldown on their shield
    # - have no stamina
    # - if they are dodging
    enabled: true
    # the duration until a block expires
    duration: 750
    # On a success / failed block, an entity is thrown back. How strong is the throw.
    throw-strength: 0.5
    # On a successful block how much damage is mitigated
    success-mitigation: 1.0
    # The stamina cost if a block is succeeded
    success-stamina-cost: 50
    # On a failed block how much damage is mitigated. (This means even if a player is still blocking they can take damage)
    fail-mitigation: 0.5
    # The stamina cost if a block is failed
    fail-stamina-cost: 100
    # If you run out of stamina and attempt to block, how long is the cooldown
    cooldown: 500
    # Which damage causes apply to a block event. See list here https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    applicable-damage-causes:
      - ENTITY_ATTACK
      - ENTITY_SWEEP_ATTACK
      - BLOCK_EXPLOSION
      - ENTITY_EXPLOSION
      - PROJECTILE